export const OBJECT_TYPE = {
  date: 'Date',
  array: 'Array',
  regexp: 'RegExp',
  map: 'Map',
  weakMap: 'WeakMap',
  set: 'Set',
  weakSet: 'WeakSet',
  error: 'Error',
  arrayBuffer: 'ArrayBuffer',
  dataView: 'DataView',
  function: 'Function',
  int8Array: 'Int8Array',
  uint8Array: 'Uint8Array',
  uint8ClampedArray: 'Uint8ClampedArray',
  int16Array: 'Int16Array',
  uint16Array: 'Uint16Array',
  int32Array: 'Int32Array',
  uint32Array: 'Uint32Array',
  float32Array: 'Float32Array',
  float64Array: 'Float64Array',
  boolean: 'Boolean',
  number: 'Number',
  string: 'String',
  symbol: 'Symbol',
  bigInt: 'BigInt',
  object: 'Object',
  null: 'Null',
  undefined: 'Undefined',
  arguments: 'Arguments',
} as const;

export type ObjectType = (typeof OBJECT_TYPE)[keyof typeof OBJECT_TYPE];
